### PR TITLE
Build script and test script similar to what economist revamp are using

### PR DESCRIPTION
**Pull request by Seanseviltwin**
(RED - Please don't actually merge.)

### CODE REVIEW

**Comment by Seanseviltwin** [comment]
(Green) - okay to merge if it works with origin/tests branch.

**Comment by Seanseviltwin** [comment]
This work includes dockerising the build and requires local docker to run.

**Comment by buddhamagnet** [comment]
@Seanseviltwin could we remove the completed function headers in handlers.go so that the only additions in this PR are the build scripts etc?

**Comment by Seanseviltwin** [comment]
Sure. I'll do that now.

**Comment by Seanseviltwin** [comment]
Add another commit so it should build locally if you have docker running.

**Comment by Seanseviltwin** [comment]
Whoop! Runs tests in docker. Good to merge.

**Pull request closed without merging**
